name: Test System Dependencies Fix

on:
  workflow_dispatch:
  
jobs:
  test-ubuntu-fix:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install CORRECT system dependencies
      run: |
        sudo apt-get update
        echo "Installing Qt6 system dependencies for Ubuntu 22.04..."
        sudo apt-get install -y \
          libegl1 \
          libgl1 \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libxcb-xfixes0 \
          libxcb-shape0 \
          libglib2.0-0 \
          libfontconfig1 \
          libxcb1 \
          libxcb-glx0 \
          libxcb-xkb1 \
          libxkbcommon0 \
          libdbus-1-3 \
          libasound2
        echo "✅ System dependencies installed successfully"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.8.0 PyQt6-sip==13.8.0
        echo "✅ PyQt6 installed"
        
    - name: Test PyQt6 in headless mode
      run: |
        export QT_QPA_PLATFORM=offscreen
        python -c "
import os
os.environ['QT_QPA_PLATFORM'] = 'offscreen'
from PyQt6.QtWidgets import QApplication
app = QApplication([])
print('✅ PyQt6 GUI works in headless mode!')
app.quit()
"
        
    - name: Test project imports
      run: |
        export QT_QPA_PLATFORM=offscreen
        python -c "import sys; sys.path.append('.'); sys.path.append('src')" 
        python -c "
import os
os.environ['QT_QPA_PLATFORM'] = 'offscreen'
import src.main_window
print('✅ main_window imports work!')
"
        
    - name: Success
      run: |
        echo "🎉 All tests passed! The system dependencies fix works!"
        echo "✅ PyQt6 installs correctly"
        echo "✅ No more libEGL.so.1 errors"
        echo "✅ Project imports work"
        echo "Ready for building executables!"